export const categoriesData = {
  "DOCUMENTAÇÃO PRELIMINAR": [
    "1.1 - INSTALAÇÃO PORTUÁRIA: Razão Social e CNPJ",
    "1.2 - SÓCIOS/PROPRIETÁRIOS/REPRESENTANTES:",
    "1.2.1 - Carteira de Identidade",
    "1.2.2 - CPF",
    "1.2.3 - Estatuto (comprovação de quem são os representantes legais)",
    "1.3 - SUPERVISORES DE SEGURANÇA PORTUÁRIA (SSP):",
    "1.3.1 - Carteira de Identidade",
    "1.3.2 - CPF",
    "1.3.3 - Certidão Negativa de Antecedentes Criminais expedida pela Justiça Federal",
    "1.3.4 - Certidão Negativa de Antecedentes Criminais Expedidas pela Justiça Estadual",
    "1.3.5 - Certificados do CESSP e CASSP do SSP (informar edições dos cursos)",
    "1.3.6 - Credencial de Segurança Portuária (CSP) dos SSP",
    "1.3.7 - Cópia do Oficio da Capitania dos Portos informando a designação do SSP",
    "1.4 - EQUIPE DE SEGURANÇA PORTUÁRIA (ESP):",
    "1.4.1 - Carteira de Identidade",
    "1.4.2 - CPF",
    "1.4.3 - Certidão Negativa de Antecedentes Criminais expedida pela Justiça Federal",
    "1.4.4 - Certidão Negativa de Antecedentes Criminais Expedidas pela Justiça Estadual",
    "1.4.5 - Certificados do CESSP da ESP (informar edições dos cursos)",
    "1.4.6 - Credencial de Segurança Portuária (CSP) da ESP",
    "1.5 - TERCEIRIZADOS:",
    "1.5.1 - Carteira de Identidade",
    "1.5.2 - CPF",
    "1.5.3 - Certidão Negativa de Antecedentes Criminais expedida pela Justiça Federal",
    "1.5.4 - Certidão Negativa de Antecedentes Criminais Expedidas pela Justiça Estadual",
    "1.5.5 - Certificados do CESSP (informar edições dos cursos)",
    "1.5.6 - Credencial de Segurança Portuária (CSP)"
  ],
  "ESTUDO DE AVALIAÇÃO DE RISCOS": [
    "2.1 - Possui EAR aprovado e atualizado?",
    "2.2 - O EAR considera como área de abrangência do Código ISPS a área outorgada integralmente como instalação portuária?",
    "2.3 - O EAR considera os ativos de interesse para o Código ISPS localizados fora da área outorgada? Quais?",
    "2.4 - O EAR considera as ameaças e vulnerabilidades de segurança portuária da instalação?",
    "2.5 - O EAR considera as medidas de segurança portuária existentes e procedimentos?",
    "2.6 - O EAR considera as medidas necessárias para proteger pessoas, cargas e provisões?",
    "2.7 - O EAR considera as medidas necessárias para proteger a área restrita e controlada?",
    "2.8 - O EAR considera as medidas necessárias para responder a incidentes de segurança?",
    "2.9 - O EAR considera as medidas necessárias para evacuação em caso de ameaças?",
    "2.10 - O EAR considera os deveres do pessoal com responsabilidades de segurança?"
  ],
  "PLANO DE SEGURANÇA PORTUÁRIA": [
    "3.1 - Possui PSP aprovado e atualizado?",
    "3.2 - O PSP indica as medidas de segurança operacionais para os níveis 1, 2 e 3?",
    "3.3 - O PSP indica as medidas para transição entre níveis de segurança?",
    "3.4 - O PSP identifica o SSP e estabelece seus deveres e responsabilidades?",
    "3.5 - O PSP estabelece procedimentos para avaliação da eficácia das medidas?",
    "3.6 - O PSP estabelece procedimentos para relatar incidentes de segurança?",
    "3.7 - O PSP identifica procedimentos para responder a alertas de segurança?",
    "3.8 - O PSP estabelece procedimentos para evacuação em caso de ameaças?",
    "3.9 - O PSP estabelece os deveres do pessoal com responsabilidades de segurança?",
    "3.10 - O PSP estabelece procedimentos para interface com atividades de segurança do navio?"
  ],
  "SEGURANÇA": [
    "4.1 - O perímetro da instalação está devidamente iluminado e protegido por muros, cercas, ofendículos, barreiras ou outros?",
    "4.2 - Os recursos indicados no item 4.1 são adequados para prevenir o acesso não autorizado às instalações?",
    "4.3 - Os recursos são adequados para proteger pessoas, cargas e provisões de bordo?",
    "4.4 - Os recursos são adequados para proteger a área restrita e controlada?",
    "4.5 - Os recursos são adequados para responder a incidentes de segurança?",
    "4.6 - Os recursos são adequados para manter operações essenciais da instalação?",
    "4.7 - Existe sistema de CFTV ou outro similar?",
    "4.8 - O CFTV possui sistema de gravação de vídeos e diagramação informatizada?",
    "4.9 - O sistema de gravação armazena dados por um período mínimo de 90 dias?",
    "4.10 - O sistema permite busca por data e horário?",
    "4.11 - O sistema permite reprodução em tempo real?",
    "4.12 - O sistema permite a impressão de imagens?",
    "4.13 - O sistema permite a gravação em mídias removíveis?",
    "4.14 - O CFTV está adequado (perímetro coberto por câmeras fixas, sem pontos cegos relevantes, com funcionamento adequado e com as devidas nitidez e resolução?",
    "4.15 - O CFTV monitora o bordo do mar dos navios atracados e a área marítima adjacente à instalação?",
    "4.16 - O CFTV monitora áreas onde pessoas, cargas, unidades de transporte de carga e provisões de bordo aguardam processamento?",
    "4.17 - Existem postos de controle de acesso em número adequado? Esses postos são devidamente guarnecidos permanentemente?",
    "4.18 - Todos os funcionários, prestadores de serviço, visitantes e demais pessoas que tenham acesso à instalação portuária são obrigados a exibir permanentemente sua identificação enquanto estiverem nas áreas restritas e controlada da instalação portuária?",
    "4.19 - A identificação mencionada no item 4.18 é fornecida pela própria instalação portuária?",
    "4.20 - A identificação é de fácil identificação e contém foto recente?",
    "4.21 - A identificação possui validade?",
    "4.22 - Existe a efetiva verificação da identificação pessoal nos pontos de controle de acesso?",
    "4.23 - Existe controle de acesso por meio de sistema informatizado em todos os pontos de acesso?",
    "4.24 - O sistema informatizado permite a identificação das pessoas que acessaram as áreas restritas e controladas?",
    "4.25 - O sistema permite a identificação dos horários de acesso às áreas restritas e controladas?",
    "4.26 - O sistema permite a identificação dos locais de acesso às áreas restritas e controladas?",
    "4.27 - O sistema permite a geração de relatórios?",
    "4.28 - O sistema permite a busca por pessoa, horário e local?",
    "4.29 - O sistema permite a impressão de dados?",
    "4.30 - O sistema permite a gravação de dados em mídias removíveis?",
    "4.31 - O sistema armazena os dados por um período mínimo de 90 dias?",
    "4.32 - Existe sistema de comunicação (rádio, telefone, etc.) para permitir comunicação efetiva dentro da instalação portuária?",
    "4.33 - O sistema de comunicação permite comunicação efetiva entre a instalação portuária e os navios?",
    "4.34 - O sistema permite comunicação efetiva entre a instalação portuária e as autoridades competentes?",
    "4.35 - O sistema permite comunicação efetiva entre a instalação portuária e as empresas de navegação?",
    "4.36 - O sistema permite comunicação efetiva entre a instalação portuária e outras instalações portuárias?",
    "4.37 - O sistema de comunicação possui sistema de backup?",
    "4.38 - A equipe de segurança realiza patrulhas rotineiras em todas as áreas (notadamente nas controladas e restritas)?",
    "4.39 - Quantos colaboradores fazem parte da equipe de segurança? Em que escala de turno trabalham? As quantidades existentes e a escalas de trabalho são adequadas?",
    "4.40 - A equipe de segurança possui conhecimento dos procedimentos de segurança portuária aplicáveis às suas funções?",
    "4.41 - O SSP realiza reuniões com a equipe da unidade de segurança? Qual a frequência? há evidências que comprovem a realização das mesmas? A frequência observada é suficiente?",
    "4.42 - A equipe de segurança possui conhecimento dos procedimentos de emergência?",
    "4.43 - A equipe de segurança possui conhecimento dos procedimentos de evacuação?",
    "4.44 - A equipe de segurança possui conhecimento dos procedimentos de comunicação?",
    "4.45 - A equipe de segurança possui conhecimento dos procedimentos de interface com as atividades de segurança do navio?",
    "4.46 - A equipe de segurança possui conhecimento dos procedimentos de resposta a incidentes de segurança portuária?",
    "4.47 - A equipe de segurança recebe treinamento frequente? (mencionar a frequência)",
    "4.48 - A equipe de segurança realiza exercícios? (mencionar a frequência e data do último exercício)",
    "4.49 - A equipe de segurança possui equipamentos de proteção individual (EPI) adequados?",
    "4.50 - A equipe de segurança possui equipamentos de comunicação adequados?"
  ],
  "COMUNICAÇÕES E TI": [
    "5.1 - Existe sistema de comunicação (rádio, telefone, etc.) para permitir comunicação efetiva dentro da instalação portuária?",
    "5.2 - O sistema de comunicação permite comunicação efetiva entre a instalação portuária e os navios?",
    "5.3 - O sistema permite comunicação efetiva entre a instalação portuária e as autoridades competentes?",
    "5.4 - O sistema permite comunicação efetiva entre a instalação portuária e as empresas de navegação?",
    "5.5 - O sistema permite comunicação efetiva entre a instalação portuária e outras instalações portuárias?",
    "5.6 - O sistema de comunicação possui sistema de backup?",
    "5.7 - Existe sistema de tecnologia da informação (TI) para gerenciar as informações de segurança portuária?",
    "5.8 - O sistema de TI permite o armazenamento seguro de informações de segurança portuária?",
    "5.9 - O sistema permite o processamento seguro de informações de segurança portuária?",
    "5.10 - O sistema permite a transmissão segura de informações de segurança portuária?",
    "5.11 - O sistema permite o acesso controlado às informações de segurança portuária?",
    "5.12 - O sistema permite a auditoria das informações de segurança portuária?",
    "5.13 - O sistema permite a recuperação das informações em caso de falha?",
    "5.14 - O sistema de TI possui sistema de backup adequado?",
    "5.15 - O sistema de TI é atualizado regularmente?",
    "5.16 - O sistema é protegido contra acesso não autorizado?",
    "5.17 - O sistema é protegido contra vírus e outros malwares?",
    "5.18 - O sistema é protegido contra ataques cibernéticos?",
    "5.19 - O sistema é protegido contra falhas de energia?",
    "5.20 - O sistema é protegido contra falhas de hardware?"
  ],
  "RECURSOS HUMANOS": [
    "6.1 - Existe pessoal suficiente para implementar as medidas de segurança portuária?",
    "6.2 - O pessoal possui qualificação adequada para suas funções?",
    "6.3 - O pessoal possui treinamento adequado para suas funções?",
    "6.4 - O pessoal possui conhecimento dos procedimentos de segurança portuária aplicáveis às suas funções?",
    "6.5 - O pessoal possui conhecimento dos procedimentos de emergência?",
    "6.6 - O pessoal possui conhecimento dos procedimentos de evacuação?",
    "6.7 - O pessoal possui conhecimento dos procedimentos de comunicação?",
    "6.8 - O pessoal possui conhecimento dos procedimentos de interface com as atividades de segurança do navio?",
    "6.9 - O pessoal possui conhecimento dos procedimentos de resposta a incidentes de segurança portuária?",
    "6.10 - O pessoal recebe treinamento frequente?",
    "6.11 - O pessoal realiza exercícios?",
    "6.12 - O pessoal possui equipamentos de proteção individual (EPI) adequados?",
    "6.13 - O pessoal possui equipamentos de comunicação adequados?",
    "6.14 - O pessoal possui equipamentos de detecção adequados?",
    "6.15 - O pessoal possui equipamentos de iluminação adequados?",
    "6.16 - O pessoal possui equipamentos de primeiros socorros adequados?",
    "6.17 - O pessoal possui equipamentos de combate a incêndio adequados?",
    "6.18 - O pessoal possui equipamentos de evacuação adequados?",
    "6.19 - O pessoal possui equipamentos de registro (câmeras, filmadoras, etc.) adequados?",
    "6.20 - O pessoal possui equipamentos de transporte adequados?"
  ],
  "PROCEDIMENTOS OPERACIONAIS": [
    "7.1 - Descrever detalhadamente."
  ]
}; 