export const categoriesData = {
  "DOCUMENTAÇÃO PRELIMINAR": [
    "1.1 - INSTALAÇÃO PORTUÁRIA: Razão Social e CNPJ",
    "1.2 - SÓCIOS/PROPRIETÁRIOS/REPRESENTANTES:",
    "1.2.1 - Carteira de Identidade",
    "1.2.2 - CPF",
    "1.2.3 - Estatuto (comprovação de quem são os representantes legais)",
    "1.3 - SUPERVISORES DE SEGURANÇA PORTUÁRIA (SSP):",
    "1.3.1 - Carteira de Identidade",
    "1.3.2 - CPF",
    "1.3.3 - Certidão Negativa de Antecedentes Criminais expedida pela Justiça Federal",
    "1.3.4 - Certidão Negativa de Antecedentes Criminais Expedidas pela Justiça Estadual",
    "1.3.5 - Certificados do CESSP e CASSP do SSP (informar edições dos cursos)",
    "1.3.6 - Informações contidas no Global Integrated Shipping Information System (GISIS). caso desatualizadas, indicar quais necessitam atualização"
  ],
  "ESTUDO DE AVALIAÇÃO DE RISCOS": [
    "2.1 - Possui EAR aprovado e atualizado?",
    "2.2 - O EAR considera como área de abrangência do Código ISPS a área outorgada integralmente como instalação portuária?",
    "2.3 - O EAR considera os ativos de interesse para o Código ISPS localizados fora da área outorgada? Quais?"
  ],
  "PLANO DE SEGURANÇA PORTUÁRIA": [
    "3.1 - Possui PSP aprovado e atualizado?",
    "3.2 - O PSP considera como área de abrangência do Código ISPS a área outorgada integralmente como instalação portuária?",
    "3.3 - Há ativos de interesse localizados fora da área outorgada? Quais?"
  ],
  "SEGURANÇA": [
    "4.1 - O perímetro da instalação está devidamente iluminado e protegido por muros, cercas, ofendículos, barreiras ou outros?",
    "4.2 - Os recursos indicados no item 4.1 são adequados para prevenir o acesso não autorizado às instalações?",
    "4.3 - O procedimento definido para cadastramento e autorização de acesso cumpre o seu mister (controle e cadastramento irrestrito de pessoas, cargas e veículos)?",
    "4.4 - O material de proteção do perímetro está em bom estado (necessário para prevenir acessos não autorizados)?",
    "4.5 - Existe inspeção periódica para verificar falhas nas defesas do perímetro?",
    "4.6 - A instalação portuária é coberta por outros meios de proteção, complementares aos do item 4.1? quais?",
    "4.7 - Existe sistema de CFTV ou outro similar?",
    "4.8 - O CFTV possui sistema de gravação de vídeos e diagramação informatizada da localização de suas câmeras?",
    "4.9 - O sistema de gravação de vídeos de CFTV armazena os dados de interesse à proteção da instalação por um período mínimo de 90 dias?",
    "4.10 - A qualidade dos vídeos armazenados é adequada para eventual apuração de incidente de proteção, permitindo a identificação de pessoas, veículos e outros meios envolvidos, inclusive à noite?",
    "4.11 - O sistema de gravação de vídeos de CFTV contempla todas as câmeras contidas no plano de segurança portuária?",
    "4.12 - Existe sistema de redundância ( backup ) da gravação dos vídeos do CFTV? qual o período de armazenamento deste sistema?",
    "4.13 - O sistema de redundância ( backup ) está localizado em local distinto do sistema de gravação primário?",
    "4.14 - O CFTV está adequado (perímetro coberto por câmeras fixas, sem pontos cegos relevantes, com funcionamento adequado e com as devidas nitidez e resolução?",
    "4.15 - O CFTV monitora o bordo do mar dos navios atracados e a área marítima adjacente à instalação?",
    "4.16 - Os operadores do CFTV e seus eventuais substitutos estão devidamente treinados para operação eficiente do sistema? Há procedimentos para os operadores do CFTV no caso de detecção de intrusão ou outra ocorrência anormal na instalação portuária?",
    "4.17 - Existem postos de controle de acesso em número adequado? Esses postos são devidamente guarnecidos permanentemente?",
    "4.18 - Todos os funcionários, prestadores de serviço, visitantes e demais pessoas que tenham acesso à instalação portuária são obrigados a exibir permanentemente sua identificação enquanto estiverem nas áreas restritas e controlada da instalação portuária?",
    "4.19 - Existe meio eficaz de identificação do nível de proteção, em todos os acessos de pedestres, veículos e embarcações?",
    "4.20 - Há solicitação de identificação pessoal (crachá ou outros) em outros locais além do de ingresso à instalação?",
    "4.21 - É procedimento normal a solicitação de identificação pessoal (crachá ou outros) no interior da instalação?",
    "4.22 - Existe a efetiva verificação da identificação pessoal nos pontos de controle de acesso?",
    "4.23 - Existe controle de acesso por meio de sistema informatizado em todos os pontos de acesso?",
    "4.24 - A identificação pessoal (crachá ou outros) é registrada com número serial e código de barras (ou outro mecanismo) e fornece controle irrestrito de pessoal à instalação, sem múltiplos acessos contínuos?",
    "4.25 - O crachá extraviado é substituído por outro com número diferente? É feita a baixa para a negativa de acesso do extraviado? Existe sistema de comunicação aos postos de controle do extravio?",
    "4.26 - O procedimento de identificação de visitantes e de fornecimento de crachá aos funcionários que tiverem esquecido sua identificação é separado? O controle é feito indistintamente e de maneira universal?",
    "4.27 - As identificações pessoais (crachá ou outros) são diferenciadas (cor ou forma) em face dos diversos locais com autorizações próprias, para facilitar a identificação?",
    "4.28 - O recolhimento das identificações pessoais (crachá ou outros) tem procedimento eficiente?",
    "4.29 - Existe previsão e efetivo para fazer o acompanhamento de pessoas na instalação portuária quando necessário (ex: visitantes, vendedores, motoristas, etc.)?",
    "4.30 - Há procedimento específico para o controle de acesso e movimentação de tripulantes? Há previsão de escolta de membros da tripulação das embarcações atracadas?",
    "4.31 - Há procedimento específico para o controle de acesso de familiares e visitantes aos tripulantes das embarcações atracadas/fundeadas? O registro de visitantes é eficiente e facilmente acessível?",
    "4.32 - O controle de acesso de veículos é eficiente?",
    "4.33 - O estacionamento é supervisionado e restrito apenas a veículos próprios e controlados? Há sistema de vigilância no estacionamento?",
    "4.34 - O procedimento de controle de tráfego na instalação é eficaz?",
    "4.35 - Os veículos não autorizados têm área própria de estacionamento?",
    "4.36 - Os postos de controle de acesso às áreas restritas e controladas estão devidamente estruturados (localização, equipamentos e insumos)?",
    "4.37 - As áreas restritas e controladas estão devidamente cercadas e sinalizadas?",
    "4.38 - A equipe de segurança realiza patrulhas rotineiras em todas as áreas (notadamente nas controladas e restritas)?",
    "4.39 - Quantos colaboradores fazem parte da equipe de segurança? Em que escala de turno trabalham? As quantidades existentes e a escalas de trabalho são adequadas?",
    "4.40 - A equipe de segurança tem identificação própria (uniforme e autorização para acesso às áreas específicas necessárias ao desempenho da função)?",
    "4.41 - O SSP realiza reuniões com a equipe da unidade de segurança? Qual a frequência? há evidências que comprovem a realização das mesmas? A frequência observada é suficiente?",
    "4.42 - Os equipamentos de comunicação do SSP com a equipe de segurança, demais funcionários e órgãos de segurança pública e de defesa são eficazes? quais são os meios utilizados?",
    "4.43 - Em caso de crise ou emergência, existe previsão de procedimentos a serem adotados?",
    "4.44 - Há registro de passagem da equipe de segurança por algum meio em pontos de controle? A ronda feita tem itinerário variado, para evitar estabelecimento de rotina?",
    "4.45 - A equipe de segurança possui treinamento e certificado válido para portar arma de fogo?",
    "4.46 - A equipe de segurança possui equipamentos adequados e dentro da validade requerida? Há caixa de areia para passagem de serviço armado?",
    "4.47 - A equipe de segurança recebe treinamento frequente? (mencionar a frequência)",
    "4.48 - A equipe de segurança realiza exercícios? (mencionar a frequência e data do último exercício)",
    "4.49 - O sistema de detecção de invasão é sinalizado e monitorado de um ponto central, de modo que a força de resposta possa ser acionada desse ponto?",
    "4.50 - Os pontos de acesso de veículos e pedestres são fechados quando não utilizados ou por ocasião da elevação do nível de proteção para 2 ou 3, conforme especificado no PSP?",
    "4.51 - As lâmpadas/iluminação por ventura impróprias são imediatamente substituídas?",
    "4.52 - Há atualização dos registros de exercícios, incidentes e demais dados exigidos no PSP? Há auditorias internas? Existe registro específico? Qual a frequência?",
    "4.53 - O pessoal que realiza a identificação de visitantes, controla portões de acesso e atende ligações telefônicas conhece os procedimentos a serem tomados em caso de: - ameaça terrorista (bomba, incêndio ou tomada de embarcações atracadas etc.)? - sequestro com reféns? - distúrbios civis (protestos, greves etc.) que resultem na necessidade de evacuação em emergência?",
    "4.54 - O pessoal componente da Unidade de Segurança possui conhecimentos e sabe como proceder para contactar os órgãos de segurança pública, defesa civil, autoridade marítima e outros de interesse do serviço?",
    "4.55 - Os procedimentos previstos para atender às disposições do PSP, por ocasião da elevação do nível de proteção para 2 ou 3 se demonstram adequados?",
    "4.56 - Os Registros de Ocorrência de Incidente de Proteção (ROIP) são emitidos no prazo de 24hs e são mantidos arquivados na instalação portuária por um período de 5 anos?",
    "4.57 - A contratação de novos colaboradores é precedida de avaliação prévia de seus eventuais antecedentes criminais?",
    "4.58 - O EAR e o PSP estão protegidos contra o acesso não autorizado?",
    "4.59 - A instalação portuária conhece os procedimentos para responder aos sinais de alarme das embarcações atracadas ou fundeadas?",
    "4.60 - A Unidade de Segurança é capaz de efetuar contato imediato com os funcionários da instalação portuária durante o horário de expediente e fora dele?",
    "4.61 - O pessoal da Unidade de Segurança possui acesso à relação de seus deveres e atribuições contida no PSP?",
    "4.62 - O Sistema de cadastramento, movimentação, armazenamento e manuseio de veículos, embarcações, equipamentos, cargas em geral, mercadorias perigosas e substâncias nocivas funciona adequadamente?",
    "4.63 - A instalação portuária possui sistema informatizado de registro de dados de segurança (registros dos controles de acessos e controle de chaves)? Os dados são mantidos por um período mínimo de 90 dias?",
    "4.64 - Os sistemas de alarme e de comunicação previstos no PSP funcionam adequadamente?"
  ],
  "COMUNICAÇÕES E TECNOLOGIA DA INFORMAÇÃO": [
    "5.1 - Existe login único por colaborador, para acesso às estações de trabalho?",
    "5.2 - As estações de trabalho estão configuradas para \"usuários\", sem direitos de administradores?",
    "5.3 - O uso de dispositivos de entrada e saída (CD-Rom, pen-drive, HD externo etc.) é autorizado pelo administrador da rede local, mediante solicitação justificada?",
    "5.4 - Existem filtros para inibir o acesso a sites de redes sociais, entretenimento e outros não afetos à atividade da instalação portuária? (Testar em uma estação de trabalho aleatória)",
    "5.5 - A administração de sistemas digitais ou dispositivos de proteção é dividida por mais de uma pessoa, evitando que um único funcionário concentre todas as informações, controles e acessos?",
    "5.6 - Ocorre a identificação dos recursos computacionais (estações de trabalho, servidores, dispositivos de conectividade etc.) como \"críticos\", para fins de elaboração e adoção de medidas de proteção?",
    "5.7 - Locais de guarda dos recursos de alta criticidade possuem mecanismos de controle e registro (compartimento segregado, barreiras físicas, alarmes de abertura não autorizada de portas, registro de entrada e saída de pessoal durante e após o expediente, senhas para servidores etc.)?",
    "5.8 - Os sistemas de controle de acesso e registro são auditáveis (registro por no mínimo 90 dias)?",
    "5.9 - Os equipamentos de conectividade utilizam gabinetes fechados com chave e lacre numerado?",
    "5.10 - O controle dessas chaves e dos lacres está implementado? É adequado?",
    "5.11 - Existem equipamentos elétricos de alta potência nas proximidades de recursos críticos, que possam interferir no funcionamento destes?",
    "5.12 - Os recursos críticos fazem uso de fontes estabilizadas e/ou nobreaks?",
    "5.13 - Ocorre a exigência de termo de responsabilidade para a execução de serviços nos recursos críticos por pessoal externo, alertando para a vedação do acesso indevido às informações da instalação portuária?",
    "5.14 - Há o estabelecimento, demarcação e monitoramento dos perímetros de segurança dos locais de guarda de recursos de alta criticidade?",
    "5.15 - As estações de trabalho e servidores fazem uso de versões atualizadas dos programas instalados?",
    "5.16 - Os acessos remotos são desabilitados para recursos de alta criticidade?",
    "5.17 - Os dispositivos de conectividade possuem senhas fortes (não usar senha padrão de fábrica)?",
    "5.18 - As estações de trabalho e servidores utilizam antivírus, firewall e antispyware ?",
    "5.19 - As estações de trabalho possuem senha de configuração de uso exclusivo do administrador da rede?",
    "5.20 - O compartilhamento de pastas e arquivos de trabalho é feito por meio de servidor de arquivo, evitando o uso de soluções inseguras para esse fim (\"rede windows\", serviços peer-to-peer - P2P, etc)?",
    "5.21 - Há o uso de sistema operacional de rede para gestão de recursos da rede local?",
    "5.22 - O acesso das estações de trabalho à internet se dá por meio do servidor da instalação portuária, vedando-se o acesso por outros meios (redes 3G/4G, redes wi-fi externas ou outras soluções que envolvam recursos externos)?",
    "5.23 - Existem rotinas de backup para servidores e estações de trabalho?",
    "5.24 - O uso de programas oriundos de fontes desconhecidas é vedado?",
    "5.25 - O uso de mídias e redes sociais é restrito às atividades de divulgação institucional?",
    "5.26 - As instalações afastadas da rede local são interligadas por meio de rede privada virtual (VPN)?",
    "5.27 - A instalação portuária é capaz de identificar usuários logados na rede local, por meio de rede wi-fi?",
    "5.28 - Há adestramento inicial (novos colaboradores) e contínuo (manutenção de uma cultura de segurança) no que tange à proteção na área de TI?",
    "5.29 - Existe controle de presença nesses adestramentos?",
    "5.30 - Colaboradores possuem conhecimento sobre as vedações explicitadas nesta lista de verificação (perguntar aleatoriamente a usuários da rede local)?",
    "5.31 - Administrador da rede local possui formação na área de TI?",
    "5.32 - A topologia da rede local e suas alterações ao longo do tempo são registradas em um histórico da rede local?",
    "5.33 - Existe plano de contingência para o Setor de TI?",
    "5.34 - Existe rotina de verificação periódica das contas de usuários e seus direitos?",
    "5.35 - Existe rotina de verificação periódica dos programas instalados nas estações de trabalho e servidores, atualizando os defasados e eliminando os desnecessários?",
    "5.36 - As mídias dos backups estão guardadas em local adequado (controle de acesso e barreiras físicas)?",
    "5.37 - Existe verificação periódica da integralidade dos backups (testes de recuperação)?",
    "5.38 - Há verificação periódica da desabilitação do acesso remoto?",
    "5.39 - Existe rotina de remoção de usuários devido a afastamento definitivo (demissão, aposentadoria etc.)?",
    "5.40 - Ocorre o uso de rede dedicada para o CFTV?",
    "5.41 - Os usuários que operam estações de trabalho assinam de Termo de Responsabilidade Individual (TRI)?",
    "5.42 - Existe rotina de auditoria interna, com emissão de relatório e controle da adoção das medidas recomendadas.",
    "5.43 - O administrador da rede possui conhecimento da necessidade de elaboração, expedição, adoção de medidas e arquivamento de registros de incidente de proteção (ROIP) relacionados ao Setor de TI da instalação portuária?",
    "5.44 - Incidentes de proteção relacionados ao Setor de TI são registrados no histórico da rede local?",
    "5.45 - Há o uso de estações de trabalho alugadas? Caso sim, há uma política de devolução desses equipamentos, de modo a impedir o acesso indevido a informações sensíveis da instalação portuária?",
    "5.46 - As rotinas de atualizações automáticas de sistemas operacionais e ferramentas de proteção (antivírus, anti-spyware, firewall etc.) estão habilitadas?"
  ],
  "OUTROS ITENS JULGADOS NECESSÁRIOS": [
    "6.1 - Descrever detalhadamente."
  ]
}; 